import { z } from 'zod';

export const PROTOCOL_VERSION = '1.0';

export const Base64UrlStringSchema = z
  .string()
  .regex(/^[A-Za-z0-9_-]+$/, 'Expected unpadded Base64URL');

/**
 * QR Code payload generated by the Desktop Agent
 */
export const PairingQrPayloadSchema = z.object({
  protocol_version: z.literal(PROTOCOL_VERSION),
  setup_token: z.uuid(),
  pc_id: z.uuid(),
  ip: z.string().regex(/^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$/),
  port: z.number().int().positive(),
  expires_at: z.iso.datetime(),
});

export type PairingQrPayload = z.infer<typeof PairingQrPayloadSchema>;

/**
 * Request sent by mobile to complete pairing
 */
export const PairingRequestSchema = z.object({
  protocol_version: z.literal(PROTOCOL_VERSION),
  pc_id: z.uuid(),
  setup_token: z.uuid(),
  device_id: z.uuid(),
  public_key: Base64UrlStringSchema, // Base64URL encoded raw Ed25519 public key
  device_name: z.string(),
});

export type PairingRequest = z.infer<typeof PairingRequestSchema>;

/**
 * Response for pairing request
 */
export const PairingResponseSchema = z.object({
  protocol_version: z.literal(PROTOCOL_VERSION),
  status: z.enum(['success', 'error']),
  message: z.string().optional(),
});

export type PairingResponse = z.infer<typeof PairingResponseSchema>;

/**
 * The inner payload to be signed for unlocking
 */
export const UnlockPayloadSchema = z.object({
  protocol_version: z.literal(PROTOCOL_VERSION),
  command: z.literal('unlock'),
  pc_id: z.uuid(),
  device_id: z.uuid(),
  timestamp: z.iso.datetime(),
  nonce: z.string(),
});

export type UnlockPayload = z.infer<typeof UnlockPayloadSchema>;

/**
 * Wrapper for signed unlock request
 */
export const SignedUnlockRequestSchema = z.object({
  payload: UnlockPayloadSchema,
  signature: Base64UrlStringSchema, // Base64URL encoded Ed25519 signature
});

export type SignedUnlockRequest = z.infer<typeof SignedUnlockRequestSchema>;

/**
 * Response for unlock request
 */
export const UnlockResponseSchema = z.object({
  protocol_version: z.literal(PROTOCOL_VERSION),
  status: z.enum(['success', 'error', 'clock_skew']),
  server_time: z.iso.datetime().optional(),
  message: z.string().optional(),
});

export type UnlockResponse = z.infer<typeof UnlockResponseSchema>;

/**
 * Common error response
 */
export const ErrorResponseSchema = z.object({
  protocol_version: z.literal(PROTOCOL_VERSION),
  error_code: z.string(),
  message: z.string(),
  server_time: z.iso.datetime().optional(),
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;
